# Practice Numpy

In [3]:
# install numpy array
!pip install numpy

In [4]:
# import numpy array

import numpy as np

In [5]:
# Create list and check it's type
list1 = [1, 2, 3, 4, 5]
print('Array:', list1)
print("Output: ", type(list1))
type(list1)

Array: [1, 2, 3, 4, 5]
Output:  <class 'list'>


list

In [6]:
# Use `array()` function to create numpy array from a list

arr1 = np.array(list1)

print('Output:')
print('Array:', arr1)
print('Type:', type(arr1))
type(arr1)
str(type(arr1)) == 'numpy.ndarray'
type(arr1)

Output:
Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


numpy.ndarray

In [7]:
# Check instance (checking type)
if isinstance(arr1, np.ndarray):
  print("arr1 is instance of numpy.ndarray")
else:
  print("It is not instance of ndarray")

arr1 is instance of numpy.ndarray


In [8]:
# Checking other instance types
a = 10
print(isinstance(a, int))

print(isinstance('My Name', str))

print(isinstance(False, bool))

print(isinstance({}, dict)) # empty flower brackets treats as dict

# if you want to create empty set use `set()`

print(isinstance((1, 2, 3), tuple))

print(isinstance({
  'A': 'a'
}, dict))
print(isinstance('Hello', object))
print(isinstance(10, object))



True
True
True
True
True
True
True
True


In [9]:
type({1, 2, 3, 4})

set

In [10]:
type({
  'A': 'a'
}) == dict

True

In [11]:
isinstance(set(), object)

True

In [12]:
# creating empty set
empty_set = set()

In [13]:
# in Python everything is an object
print(isinstance(10, object)) # int
print(isinstance('Str', object)) # str
print(isinstance(set(), object)) # set
print(isinstance({}, object)) # dict
print(isinstance(12.34, object)) # float
print(isinstance(True, object)) # bool
print(isinstance([], list)) # list
print(isinstance((), object)) # tuple

True
True
True
True
True
True
True
True


In [14]:
# checking individual types using type() function
print(type('str') == str)
print(type(10) == int)
print(type([]) == list)
print(type({}) == dict)
print(type(set()) == set)
print(type(()) == tuple)
print(type(False) == bool)
print(type(12.34) == float)

True
True
True
True
True
True
True
True


In [15]:
# checking type using isinstance

print(isinstance('my', str))

True


In [16]:
# Check type of ndarray

arr1 = np.array(list1)

print('Output', arr1)
print('Type', type(arr1))
print('Check type', type(arr1) == np.ndarray)
print('Check type using isinstance', isinstance(arr1, np.ndarray))

Output [1 2 3 4 5]
Type <class 'numpy.ndarray'>
Check type True
Check type using isinstance True


In [17]:
# Creating array of zeros, shape param is manadaroty
zeros_arr = np.zeros(shape=5)
print(zeros_arr)

[0. 0. 0. 0. 0.]


In [18]:
# Creating array of once using ones function
ones_arr = np.ones(shape=5) # shape is mandatory
print(ones_arr)

[1. 1. 1. 1. 1.]


In [19]:
# Creating Numpy array of random numbers
rand_arr1 = np.random.random()
print(rand_arr1) # Prints only one number

0.7101052463983328


In [35]:
rand_arr1 = np.random.random(size=30) # Print 10 random numbers distributed evening between 0.0 to 1.0
print(rand_arr1)

[0.06075113 0.86918296 0.26289736 0.30997343 0.40097717 0.98327898
 0.45209895 0.9327436  0.25736277 0.18855136 0.1440566  0.60023195
 0.91489725 0.2175271  0.08777518 0.53574123 0.36699787 0.06799507
 0.62680079 0.23901808 0.84458617 0.43420391 0.6585792  0.69627885
 0.86381148 0.99450832 0.47453483 0.58703589 0.1988254  0.36141752]


In [21]:
# using rand() function
rand_arr1 = np.random.rand()
print(rand_arr1)

0.9493300023192748


In [30]:
# Generate multiple randome numbers
rand_arr1 = np.random.rand(2, 3) # 2 rows and 3 columns
print(rand_arr1)

[[0.19492369 0.4882422  0.84767863]
 [0.7606789  0.63786632 0.65850044]]


In [37]:
# Standard normal distribution
arr_1 = np.random.randn(10)
arr_1

array([-0.16501799,  0.39433416, -0.47279355, -0.81113643, -0.55942293,
        0.65369038,  0.11868368,  1.66098447, -0.31787008, -2.17747183])

In [52]:
# randint returns random integerers from low (inclusive) to high(exclusive)
np.random.randint(5, 7, 2) # (start, end, size)

array([5, 6])

In [66]:
# Prints all 0 
print(np.arange(0, 1, 0.1, int))

# prints 1 to 9
print(np.arange(1, 10, 2, float)) # start, stop(exclusive), step, dtype

[0 0 0 0 0 0 0 0 0 0]
[1. 3. 5. 7. 9.]


### Attributes of Array

- size
- itemsize
- shape
- ndim
- dtype

In [90]:
# array1 = np.array([1, 2, 3, 4, 5])
# array1 = np.random.rand(2, 2, 2)
# array1 = np.random.randint(1, 20, 20)
# array1 = np.array([(4, 3, 2), (7, 5, 6)])
array1 = np.array([[4, 3, 2], [7, 5, 6]])
print(array1)
print(array1.size)
print(array1.itemsize)
print(array1.shape)
print(array1.ndim)
print(array1.dtype)

[[4 3 2]
 [7 5 6]]
6
8
(2, 3)
2
int64
