# Practice Numpy

In [2]:
# install numpy array
!pip install numpy

In [3]:
# import numpy array

import numpy as np

In [4]:
# Create list and check it's type
list1 = [1, 2, 3, 4, 5]
print('Array:', list1)
print("Output: ", type(list1))
type(list1)

Array: [1, 2, 3, 4, 5]
Output:  <class 'list'>


list

In [5]:
# Use `array()` function to create numpy array from a list

arr1 = np.array(list1)

print('Output:')
print('Array:', arr1)
print('Type:', type(arr1))
type(arr1)
str(type(arr1)) == 'numpy.ndarray'
type(arr1)

Output:
Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


numpy.ndarray

In [6]:
# Check instance (checking type)
if isinstance(arr1, np.ndarray):
  print("arr1 is instance of numpy.ndarray")
else:
  print("It is not instance of ndarray")

arr1 is instance of numpy.ndarray


In [7]:
# Checking other instance types
a = 10
print(isinstance(a, int))

print(isinstance('My Name', str))

print(isinstance(False, bool))

print(isinstance({}, dict)) # empty flower brackets treats as dict

# if you want to create empty set use `set()`

print(isinstance((1, 2, 3), tuple))

print(isinstance({
  'A': 'a'
}, dict))
print(isinstance('Hello', object))
print(isinstance(10, object))



True
True
True
True
True
True
True
True


In [8]:
type({1, 2, 3, 4})

set

In [9]:
type({
  'A': 'a'
}) == dict

True

In [10]:
isinstance(set(), object)

True

In [11]:
# creating empty set
empty_set = set()

In [12]:
# in Python everything is an object
print(isinstance(10, object)) # int
print(isinstance('Str', object)) # str
print(isinstance(set(), object)) # set
print(isinstance({}, object)) # dict
print(isinstance(12.34, object)) # float
print(isinstance(True, object)) # bool
print(isinstance([], list)) # list
print(isinstance((), object)) # tuple

True
True
True
True
True
True
True
True


In [13]:
# checking individual types using type() function
print(type('str') == str)
print(type(10) == int)
print(type([]) == list)
print(type({}) == dict)
print(type(set()) == set)
print(type(()) == tuple)
print(type(False) == bool)
print(type(12.34) == float)

True
True
True
True
True
True
True
True


In [14]:
# checking type using isinstance

print(isinstance('my', str))

True


In [15]:
# Check type of ndarray

arr1 = np.array(list1)

print('Output', arr1)
print('Type', type(arr1))
print('Check type', type(arr1) == np.ndarray)
print('Check type using isinstance', isinstance(arr1, np.ndarray))

Output [1 2 3 4 5]
Type <class 'numpy.ndarray'>
Check type True
Check type using isinstance True


In [16]:
# Creating array of zeros, shape param is manadaroty
zeros_arr = np.zeros(shape=5)
print(zeros_arr)

[0. 0. 0. 0. 0.]


In [17]:
# Creating array of once using ones function
ones_arr = np.ones(shape=5) # shape is mandatory
print(ones_arr)

[1. 1. 1. 1. 1.]


In [18]:
# Creating Numpy array of random numbers
rand_arr1 = np.random.random()
print(rand_arr1) # Prints only one number

0.30379015554536337


In [19]:
rand_arr1 = np.random.random(size=30) # Print 10 random numbers distributed evening between 0.0 to 1.0
print(rand_arr1)

[0.96534215 0.61149935 0.89921599 0.04103113 0.54700665 0.44776102
 0.35671123 0.40358045 0.19061379 0.4437382  0.75083589 0.5583258
 0.67942449 0.02644713 0.00111054 0.58706285 0.6138746  0.4077761
 0.3271107  0.23691929 0.25398118 0.55514413 0.0592602  0.18402771
 0.24071038 0.65058206 0.03660497 0.71805485 0.01276929 0.34918785]


In [20]:
# using rand() function
rand_arr1 = np.random.rand()
print(rand_arr1)

0.1416005566898173


In [21]:
# Generate multiple randome numbers
rand_arr1 = np.random.rand(2, 3) # 2 rows and 3 columns
print(rand_arr1)

[[0.65662831 0.10096068 0.36358763]
 [0.590454   0.13763383 0.90116671]]


In [22]:
# Standard normal distribution
arr_1 = np.random.randn(10)
arr_1

array([-1.94921052, -1.07377233,  0.72844448, -0.06070413,  0.83558708,
        1.47573251, -1.86003861, -0.68572261,  0.0152042 , -0.41408213])

In [23]:
# randint returns random integerers from low (inclusive) to high(exclusive)
np.random.randint(5, 7, 2) # (start, end, size)

array([5, 6])

In [24]:
# Prints all 0 
print(np.arange(0, 1, 0.1, int))

# prints 1 to 9
print(np.arange(1, 10, 2, float)) # start, stop(exclusive), step, dtype

[0 0 0 0 0 0 0 0 0 0]
[1. 3. 5. 7. 9.]


### Attributes of Array

- size
- itemsize
- shape
- ndim
- dtype

In [25]:
# array1 = np.array([1, 2, 3, 4, 5])
# array1 = np.random.rand(2, 2, 2)
# array1 = np.random.randint(1, 20, 20)
# array1 = np.array([(4, 3, 2), (7, 5, 6)])
array1 = np.array([[4, 3, 2], [7, 5, 6]])
print(array1)
print(array1.size)
print(array1.itemsize)
print(array1.shape)
print(array1.ndim)
print(array1.dtype)

[[4 3 2]
 [7 5 6]]
6
8
(2, 3)
2
int64


### NumPy array method

In [33]:
# reshape
original_arr = np.random.rand(2, 3)
original_arr

array([[0.34619569, 0.74212644, 0.04413086],
       [0.24608469, 0.74955336, 0.64492357]])

In [36]:
reshaped_arr = original_arr.reshape(3, 2)
reshaped_arr

array([[0.34619569, 0.74212644],
       [0.04413086, 0.24608469],
       [0.74955336, 0.64492357]])

In [38]:
another_arr = np.random.rand(10)
another_arr

array([0.81079911, 0.1977597 , 0.33065469, 0.45603379, 0.68704434,
       0.38449556, 0.35054268, 0.90396904, 0.00164412, 0.57066652])

In [39]:
another_arr.reshape(2, 5)

array([[0.81079911, 0.1977597 , 0.33065469, 0.45603379, 0.68704434],
       [0.38449556, 0.35054268, 0.90396904, 0.00164412, 0.57066652]])

In [42]:
# indexing of an array
another_arr[-1]

np.float64(0.5706665213740681)

In [46]:
two_d_arr = np.random.rand(3, 4)
two_d_arr

array([[0.06173413, 0.06706529, 0.9187231 , 0.70421718],
       [0.65470838, 0.44444684, 0.56858904, 0.57623849],
       [0.70329741, 0.31454687, 0.53883783, 0.91828393]])

In [54]:
print(two_d_arr[1][0:2])
print(two_d_arr[:,1:])

[0.65470838 0.44444684]
[[0.06706529 0.9187231  0.70421718]
 [0.44444684 0.56858904 0.57623849]
 [0.31454687 0.53883783 0.91828393]]


In [63]:
two_d_arr[0::2,:]

array([[0.06173413, 0.06706529, 0.9187231 , 0.70421718],
       [0.70329741, 0.31454687, 0.53883783, 0.91828393]])

In [69]:
# Comparision operator

age = np.array([13, 45, 22, 6, 14, 25])

print(age>18)

[False  True  True False False  True]


In [75]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[5, 6, 7], [8, 9, 0]])
print(m1)
print(m2)

[[1 2 3]
 [4 5 6]]
[[5 6 7]
 [8 9 0]]


In [76]:
m1 + m2

array([[ 6,  8, 10],
       [12, 14,  6]])

In [77]:
m1 * m2

array([[ 5, 12, 21],
       [32, 45,  0]])

In [78]:
m1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [79]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
# using dot product

m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m1)
print(m2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [96]:
m1.dot(m2)

array([[30, 36, 42],
       [66, 81, 96]])

In [97]:
# Arithmetic functions on array
np.power(m1, 2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [98]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
m1.min()

np.int64(1)

In [100]:
m1.max()

np.int64(6)

In [101]:
m1.sum()

np.int64(21)

In [102]:

np.concatenate([m1, m2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# piramid

n = 6
for i in range(1, n):
  for j in range(1, i+1):
    print(j, end=" ")
  print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [5]:
# reverse print the above problem

n = 6
for i in range(6, 1, -1):
  for j in range(1, i):
    print(j, end=" ")
  print()

1 2 3 4 5 
1 2 3 4 
1 2 3 
1 2 
1 


In [17]:
# print if the number is prime or not
# 2 3 5 7 (start from 2)

def is_prime_num(n):
  i = 2
  while i <= n//2:
    if n % i == 0:
      return False
    i += 1
  else:
    return True

n = 20
for i in range(2, n+1):
  if is_prime_num(i):
    print(i, end=" ")

# is_prime_num(4)


2 3 5 7 11 13 17 19 

In [1]:
# 45. Reverse a number using a while loop.
a = "123"
res = ""
i = len(a)
while(i > 0):
    res = res + a[i-1]
    i= i -1
res

'321'

# 23 May 2025

In [ ]:
a = 10
type(a) == int # not 'int'

True

In [8]:
a = 1.3+4j # anything but ends with 'j'
type(a)

complex

In [27]:
a = 'Nagesha'
type(a) == str

for i in a:
  print(i)

a[::-1]
# a[-12]

a[:3]
a[:]
a[-1:]
a = 'Sumit'
a[4:-5]

a[-1:4:2]
a[0::2]
a[1:-4:-1]
a[2:1:1]
a[2::-1]
a[2::1]
a[-2: -4: -1]
a[-1:-1:-1]
a[1::-1]
a[1:2:-1]
a[1::-1]
a = 'Sumit'
a[:1:-1]

N
a
g
e
s
h
a


'tim'

In [38]:
type(4 / 2)

float

In [45]:
4 // 2 == 2.0 # we can compare int value with float with .0

True

In [46]:
a = input()
a[1:]

'agesh'

In [51]:
ml = [1, 12, 3, 4, 5]
print(ml)
len(ml)
ml.sort()
ml

[1, 12, 3, 4, 5]


[1, 3, 4, 5, 12]

In [52]:
ml[::-1]

[12, 5, 4, 3, 1]

In [55]:
l2 = sorted(ml, reverse=True)

In [56]:
l2

[12, 5, 4, 3, 1]

In [59]:
l2.sort(reverse=True)

In [60]:
l2

[12, 5, 4, 3, 1]

In [64]:
l2.index(12)

0

In [66]:
l2.remove(0)

ValueError: list.remove(x): x not in list

In [67]:
a = "Nagesh"
' '.join(a)


'N a g e s h'

In [68]:
a = [1, 2, 3, 4, 5, 6]

In [77]:
b = list(map(str, a))

In [78]:
b

['1', '2', '3', '4', '5', '6']

In [79]:
'+'.join(b)

'1+2+3+4+5+6'

In [80]:
a

[1, 2, 3, 4, 5, 6]

In [81]:
list(map(lambda x: x // 2, a))

[0, 1, 1, 2, 2, 3]

In [86]:
def print_num(x):
  return "Hello" + str(x)

In [87]:
c = list(map(print_num, a))
c

['Hello1', 'Hello2', 'Hello3', 'Hello4', 'Hello5', 'Hello6']

In [90]:
my_dict = {
  'a': 10,
  'b': 20,
  'c': 40
}

In [91]:
my_dict

{'a': 10, 'b': 20, 'c': 40}

In [92]:
list(map(print, my_dict))

a
b
c


[None, None, None]

In [102]:
list(map(lambda x: print(x, my_dict[x]), my_dict))

a 10
b 20
c 40


[None, None, None]

In [100]:
for k, v in my_dict.items():
  print(k, v)

a 10
b 20
c 40


In [105]:
for k in my_dict:
  print(k, my_dict[k])

a 10
b 20
c 40


In [106]:
a = list()

In [107]:
type(a)

list

In [108]:
isinstance(a, list)

True

In [110]:
a = [1, 2, 3, 4]

In [111]:
my_dict = dict()

In [112]:
my_dict['a'] = 10

In [113]:
my_dict

{'a': 10}

In [114]:
type(my_dict)

dict

In [117]:
len(my_dict)

2

In [116]:
my_dict['a1'] = 10

In [118]:
my_dict.keys()

dict_keys(['a', 'a1'])

In [119]:
my_dict = {}
type(my_dict)

dict

In [120]:
my_set = {1, 2, 3, 4}
my_set

{1, 2, 3, 4}

In [122]:
my_set[4] # TypeError: 'set' object is not subscriptable

TypeError: 'set' object is not subscriptable

In [123]:
a = [10, 23, 33, 45]
b = a

In [124]:
a

[10, 23, 33, 45]

In [125]:
b

[10, 23, 33, 45]

In [127]:
a + b # concate 2 list

[10, 23, 33, 45, 10, 23, 33, 45]

In [128]:
a * 3

[10, 23, 33, 45, 10, 23, 33, 45, 10, 23, 33, 45]

In [133]:
"Nagesh".join("Nagesh")

'NNageshaNageshgNagesheNageshsNageshh'

In [139]:
min([101, -10, 10])

-10

In [ ]:
1344 // 10 # get the last digit

0

In [157]:
def sum_of_digits(n, tot_sum=0):
  if n == 0:
    return tot_sum
  last_num = n % 10
  tot_sum += last_num
  n = n // 10
  return sum_of_digits(n, tot_sum)

print(sum_of_digits(1111))


4


In [ ]:
#(n+1)!/n+1
def fact_n(n):
  if n == 0 or n == 1:
    return 1
  return n * fact_n(n - 1)

fact_n(5)

120

In [160]:
int(25**0.5) + 1

6

In [161]:
25//2

12

In [162]:
25**0.5

5.0

In [166]:
is_palindrom = lambda x: True if x == x[::-1] else False
is_palindrom('NaN')

True

In [167]:
"Hello sss".title()

'Hello Sss'